// apps/parity-local/src/App.svelte
<script lang="ts">
	import { Streamdown } from 'svelte-streamdown';
	import { onMount } from 'svelte';
	import type { ParityFixtureId } from '../../../fixtures/parity/fixture-registry.js';
	import { resolveParityFixture, listParityFixtures } from '../../parity-shared/fixtures.js';

	const fixtureOptions = listParityFixtures();

	let currentFixture = resolveParityFixture(null);
	let currentFixtureId: ParityFixtureId = currentFixture.id;

	const replaceFixtureInUrl = (fixtureId: ParityFixtureId) => {
		const url = new URL(window.location.href);
		url.searchParams.set('fixture', fixtureId);
		window.history.replaceState(null, '', url);
	};

	const applyFixture = (rawFixtureId: string | null | undefined) => {
		currentFixture = resolveParityFixture(rawFixtureId);
		currentFixtureId = currentFixture.id;
		replaceFixtureInUrl(currentFixture.id);
	};

	const handleFixtureChange = (event: Event) => {
		applyFixture((event.currentTarget as HTMLSelectElement).value);
	};

	onMount(() => {
		applyFixture(new URL(window.location.href).searchParams.get('fixture'));
	});
</script>

<div class="parity-app" data-parity-app="local">
	<div class="parity-shell">
		<header class="parity-header">
			<div>
				<h1>Local Svelte Streamdown Harness</h1>
				<p>
					Shared query route: <code>/?fixture=&lt;fixture-id&gt;</code>. The rendered output below
					is the local `svelte-streamdown` target for browser parity tests.
				</p>
			</div>

			<div class="parity-picker">
				<label for="parity-local-fixture">Fixture</label>
				<select
					id="parity-local-fixture"
					name="fixture"
					bind:value={currentFixtureId}
					on:change={handleFixtureChange}
				>
					{#each fixtureOptions as fixture}
						<option value={fixture.id}>{fixture.id}</option>
					{/each}
				</select>
			</div>
		</header>

		<div class="parity-grid">
			<section class="parity-panel">
				<h2>Source Fixture</h2>
				<p data-parity-fixture-id>{currentFixture.id}</p>
				<textarea class="parity-source" data-parity-source readonly value={currentFixture.markdown}
				></textarea>
			</section>

			<section class="parity-panel">
				<h2>Rendered Output</h2>
				<p>{currentFixture.label}</p>
				<div class="parity-rendered" data-parity-rendered>
					<Streamdown content={currentFixture.markdown} static />
				</div>
			</section>
		</div>
	</div>
</div>

// apps/parity-reference/src/App.tsx
import { useEffect, useState, type ChangeEvent } from 'react';
import { Streamdown } from 'streamdown';
import type { ParityFixtureId } from '../../../fixtures/parity/fixture-registry';
import { listParityFixtures, resolveParityFixture } from '../../parity-shared/fixtures';

const fixtureOptions = listParityFixtures();

export function App() {
	const [fixtureId, setFixtureId] = useState<ParityFixtureId>(() => resolveParityFixture(null).id);

	useEffect(() => {
		const initialFixture = resolveParityFixture(
			new URL(window.location.href).searchParams.get('fixture')
		);
		setFixtureId(initialFixture.id);
	}, []);

	const fixture = resolveParityFixture(fixtureId);

	const handleFixtureChange = (event: ChangeEvent<HTMLSelectElement>) => {
		const nextFixture = resolveParityFixture(event.currentTarget.value);
		const url = new URL(window.location.href);
		url.searchParams.set('fixture', nextFixture.id);
		window.history.replaceState(null, '', url);
		setFixtureId(nextFixture.id);
	};

	return (
		<div className="parity-app" data-parity-app="reference">
			<div className="parity-shell">
				<header className="parity-header">
					<div>
						<h1>Reference Streamdown Harness</h1>
						<p>
							Shared query route: <code>/?fixture=&lt;fixture-id&gt;</code>. The rendered output
							below is the frozen reference `streamdown` target at commit `5f64751`.
						</p>
					</div>

					<div className="parity-picker">
						<label htmlFor="parity-reference-fixture">Fixture</label>
						<select
							id="parity-reference-fixture"
							name="fixture"
							onChange={handleFixtureChange}
							value={fixtureId}
						>
							{fixtureOptions.map((option) => (
								<option key={option.id} value={option.id}>
									{option.id}
								</option>
							))}
						</select>
					</div>
				</header>

				<div className="parity-grid">
					<section className="parity-panel">
						<h2>Source Fixture</h2>
						<p data-parity-fixture-id>{fixture.id}</p>
						<textarea
							readOnly
							className="parity-source"
							data-parity-source
							value={fixture.markdown}
						/>
					</section>

					<section className="parity-panel">
						<h2>Rendered Output</h2>
						<p>{fixture.label}</p>
						<div className="parity-rendered" data-parity-rendered>
							<Streamdown mode="static">{fixture.markdown}</Streamdown>
						</div>
					</section>
				</div>
			</div>
		</div>
	);
}
